# src/face_anonymizer/cli.py
import sys
from pathlib import Path
from face_anonymizer.pipeline import VideoProcessor


def main():
    print("🎭 Face Anonymizer")
    print("=" * 50)
    print()
    
    # Check arguments
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python cli.py INPUT [method] [padding] [detector]")
        print()
        print("Arguments:")
        print("  INPUT      Video file or 0 for webcam")
        print("  method     blur, pixelate, black (default: blur)")
        print("  padding    0.0 to 1.0 (default: 0.3)")
        print("  detector   mediapipe or yolo (default: mediapipe)")
        print()
        print("Examples:")
        print("  python cli.py video.mp4")
        print("  python cli.py video.mp4 blur 0.3 yolo")
        print("  python cli.py 0 pixelate 0.4 mediapipe")
        return
    
    # Parse arguments
    input_arg = sys.argv[1]
    method = sys.argv[2] if len(sys.argv) > 2 else "blur"
    padding = float(sys.argv[3]) if len(sys.argv) > 3 else 0.3
    detector_name = sys.argv[4] if len(sys.argv) > 4 else "mediapipe"
    
    # Detect webcam or file
    try:
        input_source = int(input_arg)
        is_webcam = True
        print(f"📷 Source: Webcam {input_source}")
    except ValueError:
        input_source = input_arg
        is_webcam = False
        
        if not Path(input_source).exists():
            print(f"❌ Error: File not found: {input_source}")
            return
        
        print(f"📹 Source: {input_source}")
    
    # Validate method
    if method not in ["blur", "pixelate", "black"]:
        print(f"⚠️  Unknown method '{method}', using 'blur'")
        method = "blur"
    
    # Validate detector
    if detector_name not in ["mediapipe", "yolo"]:
        print(f"⚠️  Unknown detector '{detector_name}', using 'mediapipe'")
        detector_name = "mediapipe"
    
    # Auto-generate output name
    if is_webcam:
        from datetime import datetime
        timestamp = datetime.now().strftime("%Y-%m-%d_%Hh%Mm%Ss")
        output = f"webcam_{method}_{detector_name}_p{padding}_{timestamp}.mp4"
    else:
        output = None  # Auto-generated by pipeline
    
    print(f"🎨 Method: {method}")
    print(f"📏 Padding: {padding}")
    print(f"🔍 Detector: {detector_name}")
    print()
    print("Press 'q' to stop")
    print()
    
    # Create processor
    processor = VideoProcessor(
        method=method,
        padding=padding,
        detector_name=detector_name,
        min_confidence=0.3
    )
    
    try:
        processor.process_video(input_source, output)
    except KeyboardInterrupt:
        print("\n⚠️  Interrupted by user")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
    finally:
        processor.close()
    
    print("\n✨ Done!")


if __name__ == "__main__":
    main()