# src/face_anonymizer/cli.py
import sys
from pathlib import Path
from face_anonymizer.pipeline import VideoProcessor


def main():
    print("🎭 Face Anonymizer")
    print("=" * 50)
    print()
    
    # Check arguments
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python cli.py VIDEO.mp4 [method] [padding] [output]")
        print("  python cli.py 0 [method] [padding] [output]  # 0 = webcam")
        print()
        print("Examples:")
        print("  python cli.py video.mp4")
        print("  python cli.py video.mp4 blur 0.3")
        print("  python cli.py 0 blur 0.4 webcam_output.mp4")
        print()
        print("Methods: blur, pixelate, black")
        return
    
    # Get input source
    input_arg = sys.argv[1]
    
    # Detect if webcam (number) or video file (string)
    try:
        input_source = int(input_arg)
        is_webcam = True
        print(f"🎥 Source: Webcam {input_source}")
    except ValueError:
        input_source = input_arg
        is_webcam = False
        
        # Check if file exists
        if not Path(input_source).exists():
            print(f"❌ Error: File not found: {input_source}")
            return
        
        print(f"📹 Source: {input_source}")
    
    # Get method
    method = sys.argv[2] if len(sys.argv) > 2 else "blur"
    if method not in ["blur", "pixelate", "black"]:
        print(f"⚠️  Unknown method '{method}', using 'blur'")
        method = "blur"
    
    # Get padding
    try:
        padding = float(sys.argv[3]) if len(sys.argv) > 3 else 0.3
    except ValueError:
        print("⚠️  Invalid padding value, using 0.3")
        padding = 0.3
    
    # Get output path
    if len(sys.argv) > 4:
        output = sys.argv[4]
    else:
        # Auto-generate output name
        if is_webcam:
            # For webcam, generate timestamp-based name
            from datetime import datetime
            timestamp = datetime.now().strftime("%Y-%m-%d_%Hh%Mm%Ss")
            output = f"webcam_{method}_p{padding}_{timestamp}.mp4"
        else:
            output = None  # Will be auto-generated by pipeline
    
    print(f"🎨 Method: {method}")
    print(f"📏 Padding: {padding}")
    if output:
        print(f"💾 Output: {output}")
    print()
    print("Press 'q' in the video window to stop")
    print()
    
    # Create processor
    processor = VideoProcessor(
        method=method,
        padding=padding,
        min_confidence=0.3
    )
    
    try:
        # Process
        processor.process_video(input_source, output)
    except KeyboardInterrupt:
        print("\n⚠️  Interrupted by user")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
    finally:
        processor.close()
    
    print("\n✨ Done!")


if __name__ == "__main__":
    main()